# Generated by Django 5.2.6 on 2025-10-30 10:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('toss', '토스페이'), ('kakao', '카카오페이'), ('payco', '페이코'), ('naver', '네이버페이'), ('bank', '무통장입금')], max_length=20)),
                ('method', models.CharField(choices=[('CARD', '신용카드'), ('EASY_PAY', '간편결제'), ('TRANSFER', '계좌이체'), ('VBANK', '가상계좌')], max_length=30)),
                ('payment_key', models.CharField(max_length=100, unique=True)),
                ('amount', models.PositiveIntegerField()),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('receipt_url', models.URLField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REQUESTED', '요청됨'), ('APPROVED', '승인됨'), ('CANCELLED', '취소됨'), ('FAILED', '실패')], default='REQUESTED', max_length=20)),
                ('raw_response', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='orders.order')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(max_length=20)),
                ('event_type', models.CharField(max_length=50)),
                ('request_url', models.CharField(blank=True, max_length=255, null=True)),
                ('request_payload', models.JSONField()),
                ('response_payload', models.JSONField(blank=True, null=True)),
                ('status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('response_time_ms', models.PositiveIntegerField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='payments.payment')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
