# Generated by Django 5.2.6 on 2025-11-05 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_account_holder_payment_account_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='bank_name',
            field=models.CharField(blank=True, choices=[('KOOKMIN', '국민은행'), ('SHINHAN', '신한은행'), ('WOORI', '우리은행'), ('HANA', '하나은행'), ('NH', '농협은행'), ('IBK', '기업은행'), ('SC', 'SC제일은행'), ('SUHYUP', '수협은행'), ('DAEGU', '대구은행'), ('BUSAN', '부산은행'), ('KYONGNAM', '경남은행'), ('GWANGJU', '광주은행'), ('JEONBUK', '전북은행'), ('JEJU', '제주은행'), ('KAKAO', '카카오뱅크'), ('TOSSBANK', '토스뱅크')], help_text='Toss API 은행 코드', max_length=20, null=True),
        ),
    ]
