# Generated by Django 5.2.6 on 2025-11-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_payment_bank_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('CARD', '신용카드'), ('EASY_PAY', '간편결제'), ('TRANSFER', '계좌이체'), ('VBANK', '가상계좌'), ('VIRTUAL_ACCOUNT', '무통장입금')], max_length=30),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('REQUESTED', '요청됨'), ('WAITING_FOR_DEPOSIT', '입금대기'), ('APPROVED', '승인됨'), ('CANCELLED', '취소됨'), ('FAILED', '실패')], default='REQUESTED', max_length=20),
        ),
    ]
