# Generated by Django 5.2.6 on 2025-11-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_alter_payment_method_alter_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='earned_point',
            field=models.PositiveIntegerField(default=0, verbose_name='포인트 적립금'),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_used_point',
            field=models.BooleanField(default=False, verbose_name='포인트 사용 여부'),
        ),
        migrations.AddField(
            model_name='payment',
            name='used_point',
            field=models.PositiveIntegerField(default=0, verbose_name='사용 포인트 금액'),
        ),
    ]
