# Generated by Django 5.2.6 on 2025-10-26 08:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_merge_0015_merge_20251023_1934_0015_user_apple_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apple_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='google_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='kakao_id',
        ),
        migrations.RemoveField(
            model_name='user',
            name='naver_id',
        ),
        migrations.CreateModel(
            name='SocialUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('google', 'Google'), ('kakao', 'Kakao'), ('naver', 'Naver'), ('apple', 'Apple')], max_length=20)),
                ('social_id', models.CharField(max_length=255, unique=True, verbose_name='소셜 플랫폼 고유 ID')),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('connected_at', models.DateTimeField(auto_now_add=True)),
                ('disconnected_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_accounts', to=settings.AUTH_USER_MODEL, verbose_name='연결된 유저')),
            ],
            options={
                'verbose_name': '소셜 유저',
                'verbose_name_plural': '소셜 유저 목록',
                'constraints': [models.UniqueConstraint(fields=('provider', 'social_id'), name='unique_provider_social_id')],
            },
        ),
    ]
