# Generated by Django 5.2.6 on 2025-10-27 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_remove_user_apple_id_remove_user_google_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socialuser',
            name='social_id',
            field=models.CharField(max_length=255, verbose_name='소셜 플랫폼 고유 ID'),
        ),
    ]
