# Generated by Django 5.2.6 on 2025-10-28 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_socialuser_social_id'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='socialuser',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='unique_user_provider'),
        ),
    ]
