# Generated by Django 5.2.6 on 2025-10-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_socialuser_unique_user_provider'),
    ]

    operations = [
        migrations.CreateModel(
            name='OAuthState',
            fields=[
                ('key', models.CharField(default='5eb3256033174023baf8f6f8d65c58c1', max_length=64, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
