# Generated by Django 5.2.6 on 2025-10-28 17:57

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_oauthstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthstate',
            name='key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
