# Generated by Django 5.2.6 on 2025-10-29 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_oauthstate_key'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OAuthState',
        ),
    ]
