services:
# TODO: 이메일 인증 celery 추가 시에 같이 작성 예정
#  web:
#    container_name: django
#    env_file:
#      - .env
#    ports:
#      - "8000:8000"
#    networks:
#      - ss_networks
#    depends_on:
#      db:
#        condition: service_healthy

  db:
    container_name: postgres
    image: postgres
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres", "-d", "seoseung_su" ]
      interval: 10s
      timeout: 5s
      retries: 5

# TODO: 컨테이너 추가시
#networks:
#  - ss_networks:
#      driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume: