# Generated by Django 5.2.6 on 2026-01-23 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_userpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usedcoupon',
            name='used_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
