# Generated by Django 5.2.6 on 2025-10-30 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_alter_cart_table'),
        ('products', '0007_remove_product_color_product_colors'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.color'),
        ),
    ]
