# Generated by Django 5.2.6 on 2026-01-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_orderitem_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_status',
            field=models.CharField(choices=[('PENDING', '배송대기'), ('SHIPPING', '배송중'), ('DELIVERED', '배송완료')], default='PENDING', max_length=20),
        ),
    ]
