# Generated by Django 5.2.6 on 2026-01-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_add_shipping_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_admin_note',
            field=models.TextField(blank=True, null=True, verbose_name='관리자 메모'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_processed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='취소 처리 시간'),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.CharField(blank=True, choices=[('SIZE_MISMATCH', '사이즈가 안 맞아요'), ('NOT_LIKE_COLOR', '색상이 마음에 안 들어요'), ('NOT_LIKE_DESIGN', '디자인이 마음에 안 들어요'), ('WRONG_PRODUCT', '다른 상품이 왔어요'), ('DEFECTIVE', '제품 불량이에요'), ('WRONG_DELIVERY', '배송 오류'), ('SIMPLE_CHANGE_OF_MIND', '단순히 마음 바뀜'), ('TOO_EXPENSIVE', '너무 비싸서'), ('NO_NEED_ANYMORE', '필요 없어졌어요'), ('OTHER', '기타')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_request_status',
            field=models.CharField(choices=[('NONE', '없음'), ('PENDING', '취소요청'), ('APPROVED', '취소승인'), ('REJECTED', '취소거부')], default='NONE', max_length=20),
        ),
        migrations.AddField(
            model_name='order',
            name='cancellation_requested_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='취소 요청 시간'),
        ),
    ]
