name: oracle deploy

on:
  pull_request:
    branches:
      - main

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: OCI
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_TOKEN }}

            - name: Build and push Docker image
              run: |
                docker buildx build --platform linux/amd64,linux/arm64 -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest --push .

            - name: Deploy to Oracle Cloud
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.OCI_HOST }}
                username: ${{ secrets.OCI_USERNAME }}
                key: ${{ secrets.OCI_SSH_KEY }}
                command_timeout: 10m
                script: |
                  docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_TOKEN }}
                  docker compose down
                  docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPOSITORY }}:latest
                  docker compose up -d
                  docker image prune -af